### ISSUE TITLE
Unicode BOM (FEFF) Randomly getting inserted into markdown files

### ISSUE THREAD

**Issue by v-anpasi** [dnGrep/dnGrep#277]
I am not sure how to duplicate this bug but every once in awhile when using dnGrep and then pushing the changes to github a BOM character gets inserted.

![Screenshots1](http://imgur.com/R4nqf9A.png )

When I go to edit the file and over over the red dot I get this:

![](http://imgur.com/lUIpUuu.png)

It is an issue and affects about 33% to 66% of the files updated in bulk... I can get a round it by searching and replacing the BOM but it seems like dnGrep is at fault in these cases.  I am sorry I don't have more examples for reproducing... I will try to set up an example soon. 

(Accidently opened the bug prematurely hence all the edits)

**Comment by doug24** [comment]
Can you provide a description?  What version of dnGrep are you using?  Is this in a Replace operation?  Regex or Text?  What are you searching for/replacing with? Can you provide a sample file that we can use to reproduce the problem?

**Comment by v-anpasi** [comment]
Replace. It has happened with regex and text.  I will try to find an example I can share soon. Sorry for opening this bug prematurely (pressed **enter** accidentally).

**Comment by doug24** [comment]
What is the encoding of the original file? Is it UTF-8?  dnGrep does rewrite the entire file when doing a replace, but it does rewrite using the original (detected) encoding.   But there is no code currently to check for the BOM in the original file.

**Comment by majkinetor** [comment]
Its even worst then that, it totally scrambles the file depending on the content.

Search for _Text_ `xmlns` and replace with nothing. First part of the file appears in the middle.

I packed both original and resulting file into zip:

[bom_test.zip](https://github.com/dnGrep/dnGrep/files/1108477/bom_test.zip)


Saving file without BOM fixes the problem.

**Comment by doug24** [comment]
This is really interesting...  yes, that is a mess.

Both your input and output files are UTF-8 with a BOM.  So it looks like dnGrep is preserving the BOM from the original file.  I tried this on a couple of files with and without BOM, and it seems consistent, but need to test more.

Here's what's happening in the replace:  The first line is read with the line end character to preserve the same EOL (unix, windows, or mac) in the output file.  Then the file stream is reset by seeking to the origin.  If there is no BOM, it does reset to the start, and the replace works as expected.   But when there is a BOM, the read doesn't reset to the start, it's down near the end of the file (after the original read buffer?), then it goes back to the start.   

This is going to take some investigation.

**Comment by doug24** [comment]
This is fixed in the 2.9.64 beta, I'll leave this open while people get a chance to test it.

**Comment by doug24** [comment]
Fixed in 2.9.64 and later releases

**Comment by gstanchev** [comment]
This is still an issue in 2.9.127. I really cannot give you reproducible steps as I used dnGREP on 10-15k files and i got at least 2 with BOMs inserted.

**Comment by doug24** [comment]
The tests added when this issues was fixed are still passing.  If you or someone else has a file that I can use to reproduce the problem, please attach it and we can reopen the issue. Without a reproducible case, there isn't anything I can do.

**Comment by gstanchev** [comment]
[BOM-added-test-case.zip](https://github.com/dnGrep/dnGrep/files/3049507/BOM-added-test-case.zip)

pt25b047 - Copy.java is the starting point, "pt25b047.java" is the result after search and replace. Search for " * Copyright (C)SERENA Software,Inc. 2013-2018. All Rights Reserved." and replace with " * Copyright (C)SERENA Software,Inc. 2013-2019. All Rights Reserved." using (*) Text search. dnGREP used is 2.9.127.0

The original file is UTF-8, after the replacement it becomes UTF-8-BOM which creates issue for the Java compiler

**Comment by doug24** [comment]
Thank-you!

**Comment by gstanchev** [comment]
No, thanks for the wonderful product... let me know if you need more info...

**Comment by doug24** [comment]
The fix has been included in release 2.9.140.   The default .net UTF-8 encoder created from the character set detection code has the BOM enabled.  It has been changed to check for the BOM in the original file, and change the encoder if necessary to match the original.
